# Generated by Django 3.2.8 on 2023-07-11 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelaid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spotsname', models.CharField(max_length=50)),
                ('Spotsclimat', models.CharField(max_length=50)),
                ('Bestperiod', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50, null=True)),
                ('Visiterscount', models.CharField(max_length=50, null=True)),
                ('Rating', models.CharField(max_length=50, null=True)),
                ('Area', models.CharField(max_length=50, null=True)),
                ('View', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelaid.user')),
            ],
        ),
    ]
