# Generated by Django 3.2.8 on 2023-07-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelaid', '0002_spots'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots',
            name='Spots_status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
